template = {
    'acceleration': 0,
    'sprint_speed': 0,
    'positioning': 0,
    'finishing': 0,
    'shot_power': 0,
    'long_shots': 0,
    'volleys': 0,
    'penalties': 0,
    'vision': 0,
    'crossing': 0,
    'fk_accuracy': 0,
    'short_passing': 0,
    'long_passing': 0,
    'curve': 0,
    'agility': 0,
    'balance': 0,
    'reactions': 0,
    'ball_control': 0,
    'dribbling': 0,
    'composure': 0,
    'interceptions': 0,
    'heading_accuracy': 0,
    'def_awareness': 0,
    'standing_tackle': 0,
    'sliding_tackle': 0,
    'jumping': 0,
    'stamina': 0,
    'strength': 0,
    'aggression': 0,
}

# for max chemistry
styles = {
    'basic': {
        'sprint_speed': 5,
        'positioning': 5,
        'shot_power': 5,
        'volleys': 5,
        'penalties': 5,
        'vision': 5,
        'short_passing': 5,
        'long_passing': 5,
        'curve': 5,
        'agility': 5,
        'ball_control': 5,
        'dribbling': 5,
        'def_awareness': 5,
        'standing_tackle': 5,
        'sliding_tackle': 5,
        'jumping': 5,
        'strength': 5,
    },
    'sniper': {
        'positioning': 5,
        'shot_power': 10,
        'long_shots': 15,
        'volleys': 10,
        'penalties': 5,
        'jumping': 15,
        'strength': 5,
        'aggression': 10,
    },
    'finisher': {
        'acceleration': 5,
        'finishing': 15,
        'shot_power': 10,
        'volleys': 10,
        'penalties': 5,
        'agility': 10,
        'balance': 5,
        'dribbling': 15,
    },
    'deadeye': {
        'positioning': 10,
        'finishing': 10,
        'shot_power': 15,
        'long_shots': 5,
        'penalties': 5,
        'vision': 10,
        'short_passing': 15,
        'curve': 5,
    },
    'marksman': {
        'finishing': 10,
        'shot_power': 5,
        'long_shots': 10,
        'penalties': 5,
        'reactions': 5,
        'ball_control': 10,
        'dribbling': 10,
        'jumping': 10,
        'aggression': 10,
    },
    'hawk': {
        'acceleration': 5,
        'sprint_speed': 5,
        'positioning': 5,
        'finishing': 5,
        'shot_power': 10,
        'long_shots': 10,
        'penalties': 5,
        'jumping': 10,
        'strength': 5,
        'aggression': 10,
    },
    'hunter': {
        'acceleration': 10,
        'sprint_speed': 10,
        'positioning': 5,
        'finishing': 10,
        'shot_power': 15,
        'volleys': 15,
        'penalties': 10,
    },
    'artist': {
        'vision': 10,
        'fk_accuracy': 5,
        'short_passing': 15,
        'long_passing': 5,
        'curve': 10,
        'jumping': 10,
        'strength': 15,
        'aggression': 5,
    },
    'architect': {
        'vision': 10,
        'fk_accuracy': 5,
        'short_passing': 15,
        'long_passing': 5,
        'curve': 10,
        'jumping': 10,
        'strength': 15,
        'aggression': 5,
    },
    'powerhouse': {
        'vision': 15,
        'crossing': 5,
        'short_passing': 10,
        'long_passing': 10,
        'curve': 5,
        'interceptions': 10,
        'def_awareness': 5,
        'standing_tackle': 15,
    },
    'maestro': {
        'shot_power': 10,
        'long_shots': 10,
        'volleys': 5,
        'vision': 5,
        'fk_accuracy': 10,
        'short_passing': 5,
        'long_passing': 10,
    },
    'engine': {
        'acceleration': 5,
        'sprint_speed': 5,
        'vision': 5,
        'crossing': 10,
        'short_passing': 5,
        'long_passing': 5,
        'curve': 10,
        'agility': 5,
        'balance': 10,
        'dribbling': 10,
    },
    'catalyst': {
        'acceleration': 10,
        'sprint_speed': 10,
        'crossing': 15,
        'fk_accuracy': 10,
        'short_passing': 5,
        'long_passing': 10,
        'curve': 5,
    },
    'sentinel': {
        'interceptions': 10,
        'heading_accuracy': 15,
        'def_awareness': 10,
        'standing_tackle': 5,
        'sliding_tackle': 5,
        'jumping': 15,
        'strength': 5,
        'aggression': 10,
    },
    'guardian': {
        'balance': 10,
        'ball_control': 5,
        'dribbling': 15,
        'interceptions': 5,
        'heading_accuracy': 5,
        'def_awareness': 10,
        'standing_tackle': 15,
        'sliding_tackle': 10,
    },
    'gladiator': {
        'finishing': 15,
        'shot_power': 10,
        'volleys': 5,
        'interceptions': 10,
        'heading_accuracy': 5,
        'def_awareness': 5,
        'standing_tackle': 10,
        'sliding_tackle': 15,
    },
    'backbone': {
        'vision': 10,
        'long_passing': 10,
        'interceptions': 10,
        'def_awareness': 5,
        'standing_tackle': 10,
        'sliding_tackle': 5,
        'jumping': 10,
        'strength': 5,
        'aggression': 10,
    },
    'anchor': {
        'acceleration': 5,
        'sprint_speed': 5,
        'interceptions': 5,
        'heading_accuracy': 5,
        'def_awareness': 5,
        'standing_tackle': 10,
        'sliding_tackle': 10,
        'jumping': 10,
        'strength': 10,
        'aggression': 5,
    },
    'shadow': {
        'acceleration': 10,
        'sprint_speed': 10,
        'interceptions': 10,
        'heading_accuracy': 5,
        'def_awareness': 5,
        'standing_tackle': 10,
        'sliding_tackle': 15,
    },
}
